(()=>{"use strict";
const menu=document.querySelector(".menu-toggle");
const nav=document.querySelector(".nav");
if(!menu||!nav)return;
const close=()=>{menu.setAttribute("aria-expanded","false");menu.setAttribute("aria-label","Open menu");nav.classList.remove("open")};
menu.addEventListener("click",()=>{const expanded=menu.getAttribute("aria-expanded")==="true";menu.setAttribute("aria-expanded",String(!expanded));menu.setAttribute("aria-label",expanded?"Open menu":"Close menu");nav.classList.toggle("open",!expanded)});
nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",close));
document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});
document.addEventListener("pointerdown",e=>{if(nav.classList.contains("open")&&!nav.contains(e.target)&&!menu.contains(e.target))close()});
const desktop=window.matchMedia("(min-width: 851px)");
const handleBreakpoint=()=>{if(desktop.matches)close()};
desktop.addEventListener?.("change",handleBreakpoint);
})();
